### PR TITLE
Update Testing Branch with new Pipeline with Prettier Fix

### PR DESCRIPTION
**Pull request by Ahhorse1**

### CODE REVIEW

**Comment by Ahhorse1** [comment]
@tyler-le everything is set for the pipeline to be merged into the testing branch right?

**Comment by tyler-le** [comment]
Do you want to put #120 in the pipeline as well?

**Comment by Ahhorse1** [comment]
Yeah sure, I'll go edit those documentation files and merge it.

**Review by tyler-le — APPROVED** [review]

**Comment by tyler-le** [comment]
Ok, can I merge now?

**Comment by Ahhorse1** [comment]
Yup

**Pull request merged**
