### PR TITLE
Update Readme 

### PR DESCRIPTION
**Pull request by tyler-le**
Created a better readme for the finalized project

### CODE REVIEW

**Comment by awesomesup** [comment]
Looks good for now but im not sure if we should include a description of our app, what it does, that it runs on vanilla js html and css, its local first, stuff like that. Just so that the reader can have an idea of what our project is

**Comment by awesomesup** [comment]
Also maybe add this document in after the conflicts have been resolved. Or Merge it with main.

**Comment by tyler-le** [comment]
> Looks good for now but im not sure if we should include a description of our app, what it does, that it runs on vanilla js html and css, its local first, stuff like that. Just so that the reader can have an idea of what our project is. Just a small paragraph, like a preface to the readme document. Ofc we will have detailed explanation of each of those too in their seperate sections.

How does this look?

Screenshot 2022-11-30 at 4 01 49 PM

**Comment by tyler-le** [comment]
> Also maybe add this document in after the conflicts have been resolved. Or Merge it with main.

ill fix the conflicts before i merge

**Review by awesomesup — APPROVED** [review]
Yea that looks better. We can push this for now, and later "beautify it" if needed.

**Pull request merged**
