### PR TITLE
Puppeteer Integrated

### PR DESCRIPTION
**Pull request by tyler-le**
I integrated Puppeteer for our E2E testing.

### CODE REVIEW

**Comment by Ahhorse1** [comment]
Should you delete the testing files before we push it to pipeline?

**Comment by tyler-le** [comment]
> Should you delete the testing files before we push it to pipeline?

Yeah probably, I messaged @andreijsecor and @michaelliann to make sure that they can run the tests locally and that everything works. Once they approve, I'll delete the test files.

**Review by michaelliann — APPROVED** [review]
Puppeteer tests work for me on my local machine. Looks good waiting for @andreijsecor to test on his

**Comment by andreijsecor** [comment]
Sorry, I did not understand that I was supposed to run the tests on my machine. I just did and they worked, though I had to npm install first. Also, with the current setup, the pipeline can't run the tests because it can't create the webpage liveserver creates, so we should address that at some point.

**Review by andreijsecor — APPROVED** [review]
Seems good, not much else to say. I have a comment about the unit test file, so please look at that, but it looks like the issue I bring up will be addressed later, so it should be good to go.

**Pull request merged**
