### PR TITLE
Job Card finished 

### PR DESCRIPTION
**Pull request by tyler-le**
- Passes HTML Validation
- No JS functionality. Purely HTML/CSS
- Not mobile responsive

### CODE REVIEW

**Comment by Ahhorse1** [comment]
Should we separate the style CSS into a separate file?

**Review by Ahhorse1 — APPROVED** [review]

**Comment by tyler-le** [comment]
> Should we separate the style CSS into a separate file?

I can if you want me to. I just tried to make it identical to Lab 6

**Review by mhm1117 — APPROVED** [review]
looks good! And seemed to work well when I checked it out on codepen.

**Comment by tyler-le** [comment]
Closed because I want to integrate Tamara's and Kwan's code before we push to frontend.

**Pull request closed without merging**
