### PR TITLE
Merge latest frontend with Integration

### PR DESCRIPTION
**Pull request by Ahhorse1**

### CODE REVIEW

**Comment by tyler-le** [comment]
I think it would be easiest to merge testing into frontend **locally**, fix the conflicts on VSCode, make sure the build/test works, push merged version to frontend, and then merge frontend to testing

**Comment by tamarasagakova** [comment]
I am trying to resolve the conflicts locally right now.

**Comment by Ahhorse1** [comment]
Is this ready to be merged minus the small changes recommended by codacy and ignoring the css errors?

**Review by awesomesup — APPROVED** [review]
Does have issues with linter and prettier but tests pass

**Pull request closed without merging**
