### PR TITLE
Frontend Integration

### PR DESCRIPTION
**Pull request by tyler-le**
The frontend has been integrated and is ready to be merged into `frontend`. All CRUD components are present.
Please review, test locally, and make sure everything is good.

### CODE REVIEW

**Review by mhm1117 — APPROVED** [review]
Looks great to me! Was able to easily open it up locally and HTML/CSS seems perfectly functional!

**Review by tamarasagakova — CHANGES_REQUESTED** [review]
1. I think it would be much more efficient to have one css file instead of three for all the dialogues since they do the same exact thing.
2. index.html does not pass the HTML validation; must be fixed.

**Review by tamarasagakova — COMMENTED** [review]
Everything looks good. I believe the only things missing are media queries.

**Comment by tyler-le** [comment]
Currently fixing up some media query things / final touches. Should be ready to merge soon

**Review by tamarasagakova — APPROVED** [review]
Everything looks great. All the files has been validated; no bugs were found. Ready to merge.

**Pull request merged**
