### PR TITLE
Prettier Fix

### PR DESCRIPTION
**Pull request by tyler-le**
Prettier now only updates source code

after this and #120 , the testing branch will have to get merged with the new pipeline again

### CODE REVIEW

**Comment by tyler-le** [comment]
after this, the testing branch will have to get merged with the new pipeline again

**Review by Ahhorse1 — COMMENTED** [review]
Does the ```**/*``` affect the filepath?

**Comment by tyler-le** [comment]
> Does the `**/*` affect the filepath?

I removed `**/*.{js,md,html,css}` where `**` means to look in all directories and replaced it with `source/assets/**/*.{js,md,html,css}` which means to look in all directories under `source/assets`

**Review by mhm1117 — APPROVED** [review]
Makes sense + looks good!

**Review by Ahhorse1 — APPROVED** [review]
I see, looks good then. I'll go ahead and merge it

**Pull request merged**
