### PR TITLE
Update Integration Pipeline

### PR DESCRIPTION
**Pull request by Ahhorse1**

### CODE REVIEW

**Comment by tyler-le** [comment]
Please make sure that `pipeline-tle-jsdocs` is merged into `pipeline` before this.

**Comment by mhm1117** [comment]
There are some errors with JSDocs and jest that don't seem to be file-checks or unit tests failing. Have you looked at those/are those fine? Will they possibly be fixed with merging with pipeline-tle-jsdocs? Or do ya'll need help figuring that out?

For jest:
image

For JSDocs:
image

**Comment by tyler-le** [comment]
@mhm1117 
the jest error is because we don't have a github page for puppeteer to run on, so the link is invalid.
the jsdoc error is what i _hopefully_ fixed in #113

**Comment by tyler-le** [comment]
Looks like pipeline is ready to merge now

**Review by tyler-le — APPROVED** [review]

**Review by mhm1117 — APPROVED** [review]
I think it looks ready and we should go ahead and merge!

**Pull request merged**
