### PR TITLE
Fixed CSS Linting Errors

### PR DESCRIPTION
**Pull request by tyler-le**
Fixed all CSS Lint errors and this branch now currently passed CSSLint and ESLint.

Had to also fix some JS files since we call CSS selectors in there.

Ignore the merge conflicts, they are from the documentation and I will fix it.

### CODE REVIEW

**Review by mhm1117 — APPROVED** [review]
Looks great!
Prettier seems to have a weird error with one of the generated html documentation files but like looking at the file it seems fine? But maybe that will be fixed when merge conflicts get fixed?

**Comment by tyler-le** [comment]
> Looks great! Prettier seems to have a weird error with one of the generated html documentation files but like looking at the file it seems fine? But maybe that will be fixed when merge conflicts get fixed?

See #119 for this fix

**Comment by mhm1117** [comment]
Oops, I see. Prettier won't try to do documentation anymore. Looks great then!

**Review by Ahhorse1 — CHANGES_REQUESTED** [review]
for __tests__/unit-tests.js
does cancelBtn need to be cancel_btn since I see you changed addBtn to add_btn?

**Comment by tyler-le** [comment]
> for **tests**/unit-tests.js does cancelBtn need to be cancel_btn since I see you changed addBtn to add_btn?

good catch, will fix that and double check everything else

**Review by Ahhorse1 — APPROVED** [review]
Looks good, just wondering what were the changes they wanted in the {<nav>} tags?

**Comment by tyler-le** [comment]
> Looks good, just wondering what were the changes they wanted in the `<nav>` tags?

honestly not sure, i just ran eslint with the --fix option and it automatically fixes it for me

**Pull request merged**
