### PR TITLE
Pipeline jcyan jest

### LINKED ISSUE #20: CI/CD Pipeline - Phase 1
**We are in need of a CI/CD pipeline. We should research and implement the following for phase 1.**
1. Linting / Code Quality
2. Unit Tests
3. Document Generation

**We also need to create files/diagrams in /admin/cipipeline**
1. A diagram of our pipeline
2. A two-page md file about our pipeline and its functionalities
3. A two-minute video presentation of our pipeline

### PR DESCRIPTION
**Pull request by Ahhorse1**
Implemented Jest into pipeline. Resolves #20 as it is the last part of our Pipeline for Phase 1.
This only implements Jest, it does not include puppeteer or Babel (the other two things we worked with in the lab, those will have to be implemented separately as I was running into issues with Babel)

### CODE REVIEW

**Review by tyler-le — CHANGES_REQUESTED** [review]
Looks good but can we fix the merge conflicts?

**Comment by Ahhorse1** [comment]
I think I resolved the merge conflicts

**Review by tyler-le — APPROVED** [review]
Looks good

**Review by tyler-le — CHANGES_REQUESTED** [review]
The `package.json` is not valid and is causing the linters to fail. It should be like this (note the placement of commas in `devDependencies`

```
{
	"devDependencies": {
		"eslint": "^8.27.0",
		"eslint-config-prettier": "^8.5.0",
		"eslint-config-standard": "^17.0.0",
		"eslint-plugin-import": "^2.26.0",
		"eslint-plugin-n": "^15.5.1",
		"eslint-plugin-promise": "^6.1.1",
		"eslint-plugin-snakecasejs": "^2.2.0",
		"jest": "^29.3.1"
	},
	"scripts": {
		"test": "jest"
	},
	"dependencies": {
		"eslint-plugin-snakecase": "^0.0.1"
	}
}
```

This is also the case in `package-lock.json` as well.

**Comment by Ahhorse1** [comment]
Commas have been added, I checked the linters and they should be functional again if you want to double check.

**Review by tyler-le — APPROVED** [review]
Looks good

**Review by mhm1117 — COMMENTED** [review]
Overall, looks good from what I can tell. I don't fully understand what its referring to so just want to make sure that the errors with the jest file are fine, like it's only cause we don't have tests fully set up or something?

**Comment by Ahhorse1** [comment]
image
I'm pretty sure it's throwing errors because there aren't test files, I just pulled the most recent commit and ran it locally with test files and seems to work.

**Pull request merged**
