### PR TITLE
Merge pipeline into frontend/backend testing branch

### PR DESCRIPTION
**Pull request by tyler-le**
Pipeline is complete and we should now merge into the frontend/backend testing branch so that we can fix any linting errors, generate documentation, write tests, etc.

### CODE REVIEW

**Comment by awesomesup** [comment]
> Pipeline is complete and we should now merge into the frontend/backend testing branch so that we can fix any linting errors, generate documentation, write tests, etc.

Yep thats exactly what we talked about yesterday

**Review by awesomesup — APPROVED** [review]
All the -s are changes to formatting. Nothing was actually removed. 
Seems A-Okay !

**Comment by tyler-le** [comment]
> > Pipeline is complete and we should now merge into the frontend/backend testing branch so that we can fix any linting errors, generate documentation, write tests, etc.
> 
> Yep thats exactly what we talked about yesterday

Oh my bad, haven't looked at the meeting minutes yet so I am probably a bit behind

**Review by andreijsecor — APPROVED** [review]
Looks like it's mostly reformatting and new pipeline files (yml workflows, package json) that don't conflict with anything, so it should be good to go.

**Pull request merged**
